### ISSUE TITLE
[Bot] Send Email Notification on bot failure

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dx-mgn-pool#47]
Do we have a dedicated email address for this kinda stuff? @fleupold or @josojo

**Comment by josojo** [comment]
please ask anxo.

**Comment by fleupold** [comment]
I think dev-ops have some form of oncall process (or will probably be interested in defining one with us), so they should be looped in (I believe the existing buyer bots post in some slack channel. For now, you can also just use your email address, and we can define an alias later.

**Comment by bh2smith** [comment]
Solved by @luarx externally. Alternate solution (not merged) available in #55

**Comment by anxolin** [comment]
Yes, we use slack, we have a lot of notifications. Not only errors, also we notify every trade and we send reports. 

We are not sending mails yet, we plan to add it, maybe for 3rd parties, also for new developments we have in mind.

It should be easy using sth like this https://nodemailer.com/about and the conf provided by devops.
For a basic email with the output in case of failure, #55 seams ok. Also, note that cron can send emails in case of failure if configured.

**Comment by bh2smith** [comment]
I would be interested to see a link regarding cron emails. Was not able to find this while searching.

**Comment by anxolin** [comment]
For example: https://www.nixtutor.com/linux/sending-email-alerts-through-cron/
