### ISSUE TITLE
Gnosis Safe (Rinkeby) doesn't get recognized

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dx-mgn-pool#72]
Description:
When entering dx-mgn-pool.staging.gnosisdev.com with the Gnosis Safe rinkeby, the wallet doesn't get recognized, so in the "please select a wallet" section, you are only able to tap on "Null". When you tap on it, the wallet won't get connected with the interface and it keeps loading.

Steps to reproduce the behaviour:

Pre-Condition: Metamask extension disabled.

1. Go to dx-mgn-pool.staging.gnosisdev.com with the Safe extension enabled.
2. Tap on the null button
3. Observe

Expected behaviour:
The Safe is successfully connected with the pool interface

Actual behaviour:
The safe doesn't get connected and it keeps loading.

Platform:
- dX-MGn-pool fRontend interface -
App version: 0.0.1-RC1
Contract version: ^0.1.3-RC1
Gnosis Safe Rinkeby version: 1.3.3

Additional context:
Google Chrome Version:  72.0.3626.119

Capture
![image](https://user-images.githubusercontent.com/44403034/53499593-67eb9880-3a87-11e9-9e17-96558a268683.png)
![image](https://user-images.githubusercontent.com/44403034/53499605-6e7a1000-3a87-11e9-84dc-980f81026442.png)

**Comment by MicaelaPesado** [comment]
@germartinez @W3stside

**Comment by germartinez** [comment]
@MicaelaPesado Once the Safe extension is installed, and the Dapp whitelisted and opened, could you try to refresh the page using Ctrl + F5?

**Comment by MicaelaPesado** [comment]
I think that probably we heven't whitelisted the Dapp, yesterday, now it works fine, and we are testing the funcionality.

**Comment by W3stside** [comment]
closing for now as this issue doesn't relate to functionality but initialisation
