### ISSUE TITLE
Locking MGN doesn't work

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-mgn-pool#77]
Description: 
Locking MGN shows an error message and doesn't work. 

Steps to reproduce:

Pre-condition: Have MGN generated from recent transactions 
1-Go to https://dx-mgn-pool.staging.gnosisdev.com/
2-Check MGN balance 
3-Click on "Lock" 
4-Observe 

Expected behavior: 
MGN is succesfully locked. 

Actual behavior:
An error message is shown, MGN doesn't get locked. 

Environment: 
Google Chrome 72.0.3626.121
Metamask - Rinkeby 
Address used: 0x9F76dDBEeeAB169Ef65E9ddf04a44c826427A2FA

Capture: 
https://n9.cl/4wTqn

**Comment by Velenir** [comment]
Likely fixed during some other changes
