### ISSUE TITLE
MGN amount is incorrectly displayed 

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-mgn-pool#78]
Description:
MGN amount is shown incorrectly, being 3,61 the right number and 3613620511737334784.00 the appearing funds. 

Steps to reproduce:

Pre-condition:
Have MGN generated from recent transactions

1-Go to https://dx-mgn-pool.staging.gnosisdev.com/
2-Check MGN balance
3-Observe

Expected behavior:
MGN balance is shown properly.

Environment:
Google Chrome 72.0.3626.121
Metamask - Rinkeby
Address used: 0x9F76dDBEeeAB169Ef65E9ddf04a44c826427A2FA

Capture:
Balance shown in Etherscan 
![image](https://user-images.githubusercontent.com/44405181/54132123-69f01880-43f2-11e9-8286-9e712b671c90.png)

Balance shown in Pooling interface
https://n9.cl/4wTqn

**Comment by Velenir** [comment]
Fixed.
