### ISSUE TITLE
CTA shows "Null" but Safe Wallet is connected and works

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-mgn-pool#79]
Description:
When entering the Pooling interface with only Safe Wallet extension activated, the CTA for choosing a wallet will say "Null" instead of "Safe"; Clicking it will still lead the user through the site, with the Safe actually working. 

Steps to reproduce:

Pre-condition: 
Have every wallet but Safe Wallet disabled 
1-Go to https://dx-mgn-pool.staging.gnosisdev.com/
2-Press on "Null" CTA
3-Wait until information is loaded
4-Observe

Expected behavior:
The wallet selection CTA shows "Safe" as an option, and entering the pooling section will show the right information. 

Actual behavior:
The wallet selection CTA shows "Null" as an option, but when clicked on, it'll send the user to the pooling stage, showing her/his Safe Wallet information. 

Environment:
Google Chrome 72.0.3626.121
Metamask - Rinkeby
Address used: 0x4269265B9457f6d58F95c92880d4b277Cf77e866

Capture:
https://drive.google.com/open?id=1W2VEUyG3S7pPGgVcE3BIRbvwnHU4U_ut

**Comment by Velenir** [comment]
Fixed
