### ISSUE TITLE
WETH withdrawal with Metamask fails

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-mgn-pool#86]
**Description** 
When trying to withdraw WETH from the Pooling interface using Metamask, the transaction fails and an error message appears. 

**Steps to reproduce**
*Pre-condition:* Having Rinkeby set as environment; Make sure the app enters the withdrawal stage.

1- Enter https://dx-mgn-pool.staging.gnosisdev.com/
2- Try to withdraw WETH 
3- Confirm Metamask requests
4- Observe

**Expected result** 
WETH is succesfully withdrawn.

**Actual result**
An error message is shown after await time.

**Environment** 
Chrome version: 73.0.3683.86
App Version: 0.0.1-RC16
Contracts version: ^0.1.3-RC4
Metamask - Rinkeby 

**Capture** 
https://drive.google.com/file/d/16ryZA7I3qeb0zWtuI6UW9vOqexTmczA2/view

**Comment by W3stside** [comment]
Hi @damiandragobetzky this is the wrong repo - please file the issue under https://github.com/gnosis/dx-mgn-pool-react/issues, thanks!

**Comment by damiandragobetzky** [comment]
Sure thing!
