### ISSUE TITLE
The GNO is correctly withdrawn, but it isn't shown in the interface

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dx-mgn-pool#87]
Description
The GNO is correctly withdrawn, but it isn't shown in the interface.

Pre-conditions:
1. Had an existent GNO deposit on the interface in metamask.
2. Being on the MGN unlocked period.

Steps to reproduce:
1. Go to https://dx-mgn-pool.staging.gnosisdev.com/
2. Tap on the Withdraw button.
3. Confirm the transaction with metamask.
4. Observe.

Expected behaviour:
The transaction is correctly made and it's shown in the balance on the interface.

Actual behaviour:
The transaction is correctly withdrawn (we can see it on Etherscan) but the interface doesn't show the new balance, and still shows the withdraw button.

Environment
Chrome version: 73.0.3683.86
App Version: 0.0.1-RC16
Contracts version: ^0.1.3-RC4
Metamask - Rinkeby

Screenshots:
https://drive.google.com/open?id=1Dv9G7deZhr2tNEboqdpaaWg05dWTSVoL
https://drive.google.com/open?id=1vgCWHXrQMRmk5dkN_C-X-mS_Hzrp7cml
https://drive.google.com/open?id=1KF_AZekMCHaYpJWSxTKuXve5nGcSiJkp

**Comment by W3stside** [comment]
Hi @MicaelaPesado this is the wrong repo - should be inside https://github.com/gnosis/dx-mgn-pool-react/issues
